### ISSUE TITLE
Client error: `GetClassBaseline: FindStringIndex(117-COmniLight) failed.`

### ISSUE THREAD

**Issue by kus** [Source2ZE/ServerListPlayersFix#6] opened 2024-06-28 05:14 UTC
I added this to my server and it caused my client to crash with the error `GetClassBaseline: FindStringIndex(117-COmniLight) failed.` as a message box about 30 times as soon as I joined the server.

Up to date Metamod, CounterStrikeSharp and at the time I was running [GunGame](https://github.com/ssypchenko/cs2-gungame).

My setup is here: https://github.com/kus/cs2-modded-server

My [commit](https://github.com/kus/cs2-modded-server/commit/17eef19fe9d698676e71b18ef89d736ac6dc447d) where I added it and got the error as soon as I joined the server and then [removing](https://github.com/kus/cs2-modded-server/commit/e94c8ba58c60929a46dc1c7561f6e583c9706072) it fixed it.

**Comment by Poggicek** [comment] 2024-06-28 17:21
Couldn't reproduce locally, but just in case I did an SDK rebuild, try out the latest release to see if the issue is resolved

**Comment by ClaudiuHKS** [comment] 2024-10-05 11:30
This issue must be closed now because it's fixed.
I've even implemented all the `BUpdateUserData()` calls into a `CreateThread()` worker and still works properly.
Also, I managed to get a player name by using `INetChannelInfo::GetPlayerNetInfo::GetName()`. Works too.

**Comment by Vauff** [comment] 2024-10-06 23:36
Will just close this now, since it hasn't been re-reported since the SDK rebuild.

> This issue must be closed now because it's fixed. I've even implemented all the `BUpdateUserData()` calls into a `CreateThread()` worker and still works properly. Also, I managed to get a player name by using `INetChannelInfo::GetPlayerNetInfo::GetName()`. Works too.

Still, I don't think these functions are thread-safe, so this should be avoided.

**Closed as completed by Vauff** 2024-10-06 23:36 UTC
